### ISSUE TITLE
Update package.json to export types when using moduleResolution: bundler

### ISSUE THREAD

**Issue by acrognale** [Edgar-P-yan/xml-class-transformer#3]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `xml-class-transformer@2.0.0` for the project I'm working on.

After some research noticed that [this SO issue](https://stackoverflow.com/a/77566206/383249) seems to provide a solution for using this package under Typescript 4.7+ when using moduleResolution `bundler` 

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/xml-class-transformer/package.json b/node_modules/xml-class-transformer/package.json
index 81e5f81..045b10b 100644
--- a/node_modules/xml-class-transformer/package.json
+++ b/node_modules/xml-class-transformer/package.json
@@ -12,9 +12,18 @@
   "exports": {
     ".": [
       {
-        "import": "./dist/index.mjs",
-        "require": "./dist/index.cjs",
-        "default": "./dist/index.js"
+        "import": {
+          "types": "./types/index.d.ts",
+          "default": "./dist/index.mjs"
+        },
+        "require": {
+          "types": "./types/index.d.ts",
+          "default": "./dist/index.cjs"
+        },
+        "default": {
+          "types": "./types/index.d.ts",
+          "default": "./dist/index.js"
+        }
       },
       "./dist/index.js"
     ]
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Edgar-P-yan** [comment]
Hi 👋 Just released [the v2.1.0](https://github.com/Edgar-P-yan/xml-class-transformer/releases/tag/v2.1.0) version with this fix.
Thanks for the patch, I appreciate your help!
